[tool.poetry]
name = "blue-book"
version = "0.1.0"
description = ""
authors = ["QasimTylex <mohammad.qasim@tylextech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.28.1"
pymongo = "^4.11"
python-dotenv = "^1.0.1"
undetected-chromedriver = "^3.5.5"
pandas = "^2.2.3"
openpyxl = "^3.1.5"
webdriver-manager = "^4.0.2"
xlsxwriter = "^3.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
